// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmITcv0CRI1HROGVJ-FKYZzkMeunCICiY',
    appId: '1:141000027202:web:7d283c7ba5c7cd4fa791db',
    messagingSenderId: '141000027202',
    projectId: 'world-cup-5ff09',
    authDomain: 'world-cup-5ff09.firebaseapp.com',
    storageBucket: 'world-cup-5ff09.appspot.com',
    measurementId: 'G-Q1XGSNKKF5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJXC7ei0dJCcVIpGZp_vN2U-KXYIW42HM',
    appId: '1:141000027202:android:9ca0c2ad91e5042aa791db',
    messagingSenderId: '141000027202',
    projectId: 'world-cup-5ff09',
    storageBucket: 'world-cup-5ff09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ7qOuFlileHFUBAVzrj9b71xHfofHHZ8',
    appId: '1:141000027202:ios:6e17b0f93ca42953a791db',
    messagingSenderId: '141000027202',
    projectId: 'world-cup-5ff09',
    storageBucket: 'world-cup-5ff09.appspot.com',
    iosClientId: '141000027202-c2vgjm93s5r4psiv09hlco7b4d61eb7a.apps.googleusercontent.com',
    iosBundleId: 'com.example.worldCup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ7qOuFlileHFUBAVzrj9b71xHfofHHZ8',
    appId: '1:141000027202:ios:6e17b0f93ca42953a791db',
    messagingSenderId: '141000027202',
    projectId: 'world-cup-5ff09',
    storageBucket: 'world-cup-5ff09.appspot.com',
    iosClientId: '141000027202-c2vgjm93s5r4psiv09hlco7b4d61eb7a.apps.googleusercontent.com',
    iosBundleId: 'com.example.worldCup',
  );
}
